version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: storage_postgres
    restart: always
    environment:
      POSTGRES_USER: storageUser
      POSTGRES_PASSWORD: storagePassword
      POSTGRES_DB: storage_db
    ports:
      - "5502:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: