version: "3"

services:
  mongo:
    image: mongo:6
    container_name: system-settings-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
    mongo_data:
#  apisix:
#    image: apache/apisix:3.11.0-debian
#    restart: always
#    volumes:
#      - ./conf/apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
#    depends_on:
#      - etcd
#    ports:
#      - "9180:9180/tcp"
#      - "9080:9080/tcp"
#      - "9443:9443/tcp"
#    networks:
#      apisix:
#
#  etcd:
#    image: rancher/coreos-etcd:v3.4.15-arm64
#    user: root
#    restart: always
#    volumes:
#      - ./etcd_data:/etcd-data
#    environment:
#      ETCD_UNSUPPORTED_ARCH: "arm64"
#      ETCD_ENABLE_V2: "true"
#      ALLOW_NONE_AUTHENTICATION: "yes"
#      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
#      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
#      ETCD_DATA_DIR: "/etcd-data"
#    ports:
#      - "2379:2379/tcp"
#    networks:
#      apisix:
#
#  apisix-dashboard:
#    image: apache/apisix-dashboard:3.0.1-alpine  # Dashboard’un güncel bir sürümü
#    restart: always
#    depends_on:
#      - apisix
#      - etcd
#    volumes:
#      - ./conf/dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml:ro
#    ports:
#      - "9000:9000/tcp"  # Dashboard’a erişim portu
#    networks:
#      - apisix

#networks:
#  apisix:
#    driver: bridge