server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=User-Agent, Custom-Gateway-Agent
      routes:
        - id: auth-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/auth/**, /api/v1/role/**, /api/v1/role-access/**, /api/v1/operation/**, /api/v1/user/**
        - id: reservation-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/reservation/**
        - id: infrastructure-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/translation/**
grpc:
  client:
    authService:
      address: static://localhost:9090
      negotiationType: PLAINTEXT

logging:
  level:
    root: INFO