version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: reservation-db
    restart: always
    environment:
      POSTGRES_DB: reservation_db
      POSTGRES_USER: reservation_user
      POSTGRES_PASSWORD: reservation_password
    ports:
      - "5504:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
