version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: auth_postgres
    restart: always
    environment:
      POSTGRES_USER: authUser
      POSTGRES_PASSWORD: authPassword
      POSTGRES_DB: auth_db
    ports:
      - "5503:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: